const MODELS=window.ARCHIVE_MODELS.map(([id,name])=>({id,name}));
const cfg=window.ARCHIVE_CONFIG;
const metadataReady=window.MODEL_METADATA?Promise.resolve():new Promise(resolve=>{const s=document.createElement('script');s.src='model-metadata.js';s.onload=resolve;s.onerror=resolve;document.head.appendChild(s)});
const FALLBACK_THUMBS={ffb50bc159ea47dea6cc78bd49389c5f:'https://media.sketchfab.com/models/ffb50bc159ea47dea6cc78bd49389c5f/thumbnails/4b013f078d59448385bb5b1d2b399d40/cb9cd8f299804efd9077f6598fa6ad07.jpeg'};
const viewer=document.querySelector('#fighter-viewer'),nameEl=document.querySelector('#fighter-name'),numberEl=document.querySelector('#fighter-number'),currentEl=document.querySelector('#selection-current'),totalEl=document.querySelector('#selection-total'),roster=document.querySelector('#roster-grid'),sourceLink=document.querySelector('#sketchfab-link'),loading=document.querySelector('#fighter-loading'),descriptionEl=document.querySelector('#model-description'),vertexEl=document.querySelector('#vertex-count'),triangleEl=document.querySelector('#triangle-count'),barsEl=document.querySelector('#power-bars');
const tagsEl=document.createElement('div');tagsEl.className='model-tags';descriptionEl.after(tagsEl);
const downloadsEl=document.createElement('a');downloadsEl.className='download-counter is-loading';downloadsEl.target='_blank';downloadsEl.rel='noopener';downloadsEl.innerHTML='<span>SKETCHFAB DOWNLOADS</span><strong>•••</strong><small>VIEW MODEL ↗</small>';sourceLink.after(downloadsEl);
const likesEl=document.createElement('a');likesEl.className='download-counter like-counter is-loading';likesEl.target='_blank';likesEl.rel='noopener';likesEl.innerHTML='<span>SKETCHFAB LIKES</span><strong>•••</strong><small>VIEW MODEL ↗</small>';downloadsEl.after(likesEl);
const arena=document.querySelector('.fighter-arena'),rosterSection=document.querySelector('.roster-section'),descriptionWrap=document.querySelector('.model-description-wrap');
arena.setAttribute('role','dialog');arena.setAttribute('aria-modal','true');arena.setAttribute('aria-label','Selected 3D model');arena.setAttribute('aria-hidden','true');descriptionWrap.classList.add('popover-intel');arena.append(descriptionWrap);
const closeModalButton=document.createElement('button');closeModalButton.type='button';closeModalButton.className='model-modal-close';closeModalButton.setAttribute('aria-label','Close 3D model');closeModalButton.innerHTML='<span>×</span><small>CLOSE</small>';arena.prepend(closeModalButton);
function openModelModal(){document.body.classList.add('model-modal-open');arena.setAttribute('aria-hidden','false');setTimeout(()=>closeModalButton.focus(),60)}
function closeModelModal(){document.body.classList.remove('model-modal-open');arena.setAttribute('aria-hidden','true');viewer.src='about:blank'}
closeModalButton.addEventListener('click',closeModelModal);arena.addEventListener('click',e=>{if(e.target===arena)closeModelModal()});
let selected=0;totalEl.textContent=MODELS.length;document.querySelector('#archive-count').textContent=MODELS.length;document.querySelector('#restricted-note').textContent=cfg.note;
roster.innerHTML=MODELS.map((m,i)=>`<button type="button" data-fighter="${i}" aria-label="Select ${m.name}"><img alt="" loading="lazy"><span>${String(i+1).padStart(2,'0')}</span><b>${m.name}</b><i></i></button>`).join('');
const cache=new Map();const hash=(text,s=0)=>{let h=2166136261+s;for(const c of text){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return Math.abs(h)};
function renderStats(m){barsEl.innerHTML=cfg.stats.map((label,i)=>{const n=38+(hash(m.id,i*991)%61);return`<label>${label}<i><b style="width:${n}%"></b></i><strong>${n}</strong></label>`}).join('')}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function metadata(m){if(cache.has(m.id))return cache.get(m.id);const p=metadataReady.then(()=>window.MODEL_METADATA?.[m.id]||(FALLBACK_THUMBS[m.id]?{thumb:FALLBACK_THUMBS[m.id]}:null));cache.set(m.id,p);return p}
const socialCache=new Map();
function animateCounter(el,value){const target=Number(value)||0,start=Number(el.dataset.value)||0,began=performance.now();el.dataset.value=String(target);el.classList.remove('is-loading','is-unavailable');el.classList.add('is-live');const tick=now=>{const p=Math.min(1,(now-began)/750),e=1-Math.pow(1-p,3);el.querySelector('strong').textContent=Math.round(start+(target-start)*e).toLocaleString();if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)}
async function activeSocial(m,index){const url=`https://sketchfab.com/3d-models/${m.id}`;[downloadsEl,likesEl].forEach(el=>{el.href=url;el.classList.add('is-loading');el.classList.remove('is-live','is-unavailable');el.querySelector('strong').textContent='•••'});try{if(!socialCache.has(m.id))socialCache.set(m.id,fetch(`https://api.sketchfab.com/v3/models/${m.id}`).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()}));const data=await socialCache.get(m.id);if(index!==selected)return;animateCounter(downloadsEl,data.downloadCount);animateCounter(likesEl,data.likeCount)}catch{if(index!==selected)return;[downloadsEl,likesEl].forEach(el=>{el.classList.remove('is-loading');el.classList.add('is-unavailable');el.querySelector('strong').textContent='NOT PUBLISHED'})}}
async function activeMetadata(m,index){descriptionEl.textContent='Loading bundled model data…';tagsEl.innerHTML='';vertexEl.textContent=triangleEl.textContent='—';const d=await metadata(m);if(index!==selected)return;descriptionEl.textContent=d?.desc||'No model description has been provided.';vertexEl.textContent=d?.vert||'Not published';triangleEl.textContent=d?.tri||'Not published';tagsEl.innerHTML=(d?.tags||[]).slice(0,14).map(t=>`<span>${t}</span>`).join('')}
function holdViewport(y){scrollTo(0,y);const lock=setInterval(()=>scrollTo(0,y),50);setTimeout(()=>clearInterval(lock),1800)}
function selectModel(index,scroll=false){const stableY=scrollY;selected=(index+MODELS.length)%MODELS.length;const m=MODELS[selected],n=String(selected+1).padStart(2,'0');loading.classList.remove('hidden');viewer.src=`https://sketchfab.com/models/${m.id}/embed?autostart=1&ui_theme=dark&ui_infos=0&ui_watermark=0&ui_hint=0`;nameEl.textContent=m.name;numberEl.textContent=currentEl.textContent=n;sourceLink.href=`https://sketchfab.com/3d-models/${m.id}`;renderStats(m);activeMetadata(m,selected);activeSocial(m,selected);document.querySelector('[data-fighter].active')?.classList.remove('active');const tile=document.querySelector(`[data-fighter="${selected}"]`);tile.classList.add('active');if(scroll)tile.scrollIntoView({behavior:'smooth',block:'nearest'});else holdViewport(stableY);document.documentElement.style.setProperty('--fighter-hue',String((selected*37+cfg.hue)%360))}
viewer.addEventListener('load',()=>loading.classList.add('hidden'));document.querySelector('#prev-fighter').addEventListener('click',()=>selectModel(selected-1,false));document.querySelector('#next-fighter').addEventListener('click',()=>selectModel(selected+1,false));roster.addEventListener('click',e=>{const b=e.target.closest('[data-fighter]');if(b){selectModel(Number(b.dataset.fighter),false);openModelModal()}});addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('model-modal-open'))closeModelModal();if(!document.body.classList.contains('model-modal-open'))return;if(e.key==='ArrowLeft')selectModel(selected-1,false);if(e.key==='ArrowRight')selectModel(selected+1,false)});
const tiles=[...document.querySelectorAll('[data-fighter]')];let cursor=0;async function worker(){while(cursor<tiles.length){const i=cursor++,tile=tiles[i],m=MODELS[i],d=await metadata(m),image=d?.thumb||FALLBACK_THUMBS[m.id];if(image){const img=tile.querySelector('img');img.src=image;img.alt=`Preview of ${m.name}`;tile.classList.add('has-portrait')}}}selectModel(0);setTimeout(()=>Array.from({length:6},worker),50);
