// Catalog snapshot sourced from the public Background People Gumroad storefront.
// Add or edit products here; the interface and counts update automatically.
window.PRODUCTS = [
  {name:"The Background People add-on for Blender", price:"$8.09+", category:"software", tag:"CHARACTERS", icon:"people", featured:true, image:"https://public-files.gumroad.com/5j4jsu2ctmj2oqvqg5m77xtj64nr", desc:"Fill scenes with animated background characters without breaking your workflow.", url:"https://backgroundpeople.gumroad.com/l/backgroundpeople-add-on-for-blender"},
  {name:"FBX Asset Library for Blender", price:"$3.47", category:"software", tag:"ASSET MANAGER", icon:"library", featured:true, image:"https://public-files.gumroad.com/gs2ae0ylvxkzkswt4b1n2p6j32eh", desc:"Browse, search and import FBX, GLTF, GLB and OBJ libraries from Blender's N-panel.", url:"https://backgroundpeople.gumroad.com/l/fbx-asset-library-blender-addon"},
  {name:"Music Sync Pro", price:"$4.62+", category:"software", tag:"ANIMATION", icon:"wave", desc:"A Blender add-on built for faster, music-driven animation workflows.", url:"https://backgroundpeople.gumroad.com/"},
  {name:"Animated Animals for Blender", price:"$2.31", category:"software", tag:"ANIMATION", icon:"animal", image:"https://public-files.gumroad.com/345sfl2f3rtc5hy9ma8hl77ac1o9", desc:"Bring lively animated animals into Blender scenes with less setup.", url:"https://backgroundpeople.gumroad.com/l/animated-animals-for-blender-add-on"},
  {name:"BOOLER for Blender", price:"FREE", category:"software", tag:"MODELING", icon:"bool", desc:"A free utility designed to make boolean modeling in Blender more direct.", url:"https://backgroundpeople.gumroad.com/"},
  {name:"PNGs to MP4", price:"FREE", category:"software", tag:"UTILITY", icon:"frames", desc:"Turn PNG image sequences into ready-to-share MP4 video files.", url:"https://backgroundpeople.gumroad.com/"},
  {name:"Uasset Animations to FBX Exporter", price:"€5+", category:"software", tag:"UNREAL ENGINE", icon:"frames", image:"https://public-files.gumroad.com/105s0jwe250lkr4nupk5exsdr37f", desc:"Convert Unreal Engine Uasset animation files into portable FBX animations for your 3D workflow.", url:"https://backgroundpeople.gumroad.com/l/uasset-to-fbx-exporter-unreal-engine-animations-to-fbx-exporter"},
  {name:"Sketchfab Collection Browser", price:"FREE", category:"software", tag:"ASSET BROWSER", icon:"library", image:"https://public-files.gumroad.com/y2n5o9yz9klg3vky5xbulix8yejs", desc:"Browse Sketchfab collections from inside Blender and bring online assets closer to your viewport.", url:"https://backgroundpeople.gumroad.com/l/sketchfab-collection-browser-for-blender"},
  {name:"Background People + Business bundle", price:"$10.40+", category:"software", tag:"BUNDLE", icon:"bundle", image:"https://public-files.gumroad.com/8ey7qewca2n8u52e0pjn54w314jm", desc:"The core character add-on plus 30 business characters and 170+ animations.", url:"https://backgroundpeople.gumroad.com/l/background-people-for-blender-expansion-pack-business-bundle"},
  {name:"Business People expansion pack", price:"$3.47+", category:"models", tag:"CHARACTERS", icon:"business", image:"https://public-files.gumroad.com/p5xvqopmw9nny5zf5fpmpj0slek6", desc:"Expand your scenes with 30 business-ready animated background characters.", url:"https://backgroundpeople.gumroad.com/l/background-people-business-expansion-pack"},
  {name:"Next Spring Tree Collection", price:"FREE", category:"models", tag:"NATURE", icon:"trees", featured:true, image:"https://public-files.gumroad.com/d4rieafryddmeu70k32mlfnozrzg", desc:"37 realistic, low-poly trees packed as a drag-and-drop Blender asset library.", url:"https://backgroundpeople.gumroad.com/l/tree-collection-blender"},
  {name:"Thiings 3D Logos — Volume 1", price:"$2.31+", category:"models", tag:"PROPS", icon:"things", image:"https://public-files.gumroad.com/iszpfwyd3twpbwmu1icizmulvyp6", desc:"25 playful low-poly objects supplied as a Blender asset library and FBX files.", url:"https://backgroundpeople.gumroad.com/l/3D-logos-thiings"},
  {name:"Stylized Rocks Pack 1", price:"FREE", category:"models", tag:"ENVIRONMENT", icon:"rocks", image:"https://public-files.gumroad.com/5uezayd7n3iamf6uir9qd4xfuntq", desc:"A varied collection of generated stylized rocks for Blender and FBX workflows.", url:"https://backgroundpeople.gumroad.com/l/stylized-rock-pack-free"},
  {name:"Cartoon Interiors: Indoor Plants", price:"FREE", category:"models", tag:"INTERIORS", icon:"plants", image:"https://public-files.gumroad.com/8snbgg2m7crw2zjv82wx5smtfrak", desc:"Twelve cheerful cartoon-style plants and cabinets for interior scenes.", url:"https://backgroundpeople.gumroad.com/l/cartoon-indoor-plants"},
  {name:"26 Organic Alien Materials — 2K", price:"FREE", category:"models", tag:"MATERIALS", icon:"alien", image:"https://public-files.gumroad.com/iajxz9x20b5o8iqyufmeslip5cls", desc:"A set of otherworldly organic materials ready for science-fiction projects.", url:"https://backgroundpeople.gumroad.com/l/lwyeed"},
  {name:"Sci-fi Materials — Volume 2", price:"$2.31+", category:"models", tag:"MATERIALS", icon:"scifi", image:"https://public-files.gumroad.com/mx8f7mf2ah1l6un752ks2k6ap73u", desc:"32 high-quality 2K materials with full PBR maps and a Blender asset library.", url:"https://backgroundpeople.gumroad.com/l/sci-fi-materials-png-blender"},
  {name:"Deep Space HDRI & Skybox Collection", price:"$5.76+", category:"models", tag:"ENVIRONMENT", icon:"space", image:"https://public-files.gumroad.com/x6fuv7lhodisvnzhhav3upn89tav", desc:"Twenty 8K deep-space HDRIs and skyboxes with depth maps for epic world building.", url:"https://backgroundpeople.gumroad.com/l/deep-space-nebula-hdri-skybox-collection"},
  {name:"Cool Alien Spaceship by Jungle Jim", price:"FREE", category:"models", tag:"SCI-FI MODEL", icon:"space", image:"https://public-files.gumroad.com/hxhz85oyixewo1p9r8hw5u33qvrv", desc:"A characterful alien spacecraft ready to land in Blender scenes and science-fiction projects.", url:"https://backgroundpeople.gumroad.com/l/cool-alien-spaceship-jungle-jim"},
  {name:"Alien Rock Planets — 2K", price:"FREE", category:"models", tag:"SCI-FI TEXTURES", icon:"alien", image:"https://public-files.gumroad.com/5p15ui4uotjgn6oba87rcshb83hq", desc:"A free collection of 2K alien rock and planet textures for creating strange new worlds.", url:"https://backgroundpeople.gumroad.com/l/alien-rock-planets-textures-sci-fi"}
];
